<?php
/**
 * @category   design
 * @package    custom_default
 * @author     Vikas Bansal 
 * @created    June 18, 2014 
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
</div>
<?php
$formdata = Mage::getSingleton('core/session')->getData('contactForm');
$formdata = $formdata ? $formdata : new Varien_Object();
?>
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post" enctype="multipart/form-data">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?><?php echo $formdata->getName() ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?><?php echo $formdata->getEmail() ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            <li>
                <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="<?php echo $formdata->getTelephone() ?>" class="input-text" type="text" />
                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"><?php echo $formdata->getComment() ?></textarea>
                </div>
            </li>
            <li>
                <input type="button" class="adder" value="Add Attachment(s)"/>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
    </div>
</form>
<ul id="attachment-template" style="display: none;">
    <li class="qa">
        <label for="attachment"><?php echo Mage::helper('contacts')->__('Attachment') ?></label>
        <div class="input-box">                    
            <input name="attachment[]" id="attachment" class="input-text" type="file" />
        </div>
        <input type="button" class="remover" value="Remove Attachment"/>
    </li>
</ul>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<script type="text/javascript">
//<![CDATA[
    var $j = jQuery.noConflict();
    var contactForm = new VarienForm('contactForm', true);

    $j(function($) {
        $('.adder').on('click', function() {
            var liHtml = $('#attachment-template').html();
            $('.fieldset .form-list').append(liHtml);
        })
        $('.remover').live('click', function() {
            $(this).parent().remove();

        })
    })

//]]>
</script>
